### PR TITLE
N64 :Refactor mempak title to cpak

### PR DESCRIPTION
**Pull request by networkfusion**
The N64 expected name for a "Memory Pak" is officially "Controller Pak".
This PR changes the code to be inline with the expected. (although does not change the filenames `n64_mempak.*` to make the PR easier to review).

It also:
* Improves some documents touched by this.
* Adds the STM builds to CI (split into seperate PR).

Breaking change in this PR would be the filename used on the SD Card for saves (although the original can be renamed, or possibily kept the same if required for compatibility/handled).

Also note that when a CPak does not already exist on SD Card, it is currently not initialized properly and causes games to want to repair a damaged pak (which might not be possible in certain games). Please look at https://github.com/rasky/libdragon/pull/7 for ideas on how to fix it.

### CODE REVIEW

**Comment by Ryzee119** [comment]
Thanks for this!
Are you able to change the commit titles? My convention is roughtly `SECTION: Description`
Maybe something like this:
N64 :Refactor mempak title to cpak
STM32FXX: Add builds to CI

We could also change the n64_mempack filenames in a follow up

**Comment by networkfusion** [comment]
I have added a new PR for the CI change. If you are happy with the other changes in this PR, I will rename the file and upload as a clean commit (new PR, as I get scared of Git rebase!)...

**Comment by Ryzee119** [comment]
>I have added a new PR for the CI change (since it is ready). If you are happy with the other changes in this PR, I will rename the files and upload as a clean commit (new PR, as I get scared of Git rebase!)...

Happy with the changes :)

**Comment by networkfusion** [comment]
Going with "Squash & Merge" being easiest...

**Pull request merged**
